### ISSUE TITLE
Facebook scrape ping gets triggerd on build

### ISSUE THREAD

**Issue by TheBnl** [jonom/silverstripe-share-care#26]
On builds the scrape ping get's triggerd, on a site with many pages i get errors like "Client error 403 Forbidden, Application request limit reached". 

I haven't gotten around checking why this get's triggered on build, maybe it isn't that important on a live site as the error is soft. But on a dev site it's pretty annoying, maybe adding `if (!Director::isDev())` would suffice.

**Comment by TheBnl** [comment]
Full error:
```
ERROR [User Warning]: Client error: `GET https://graph.facebook.com/?id=MY_DOMAIN&scrape=1` resulted in a `403 Forbidden` response:
{"error":{"message":"(#4) Application request limit reached","type":"OAuthException","is_transient":true,"code":4,"fbtra (truncated...)

IN GET dev/build
Line 105 in /home/vagrant/Sites/MY_DOMAIN/httpdocs/vendor/jonom/silverstripe-share-care/src/ShareCare.php

Source
======
  96:                  $client = new Client();
  97:                  try {
  98:                      $client->request('GET', 'https://graph.facebook.com/', [
  99:                          'query' => [
  100:                             'id' => $this->owner->AbsoluteLink(),
  101:                             'scrape' => true,
  102:                         ]
  103:                     ]);
  104:                 } catch (\Exception $e) {
* 105:                     user_error($e->getMessage(), E_USER_WARNING);
  106:                 }
  107:             }
  108:         }
  109:     }
  110: 
  111:     /**

Trace
=====
user_error(Client error: `GET https://graph.facebook.com/?id=MY_DOMAIN&scrape=1` resulted in a `403 Forbidden` response:
{"error":{"message":"(#4) Application request limit reached","type":"OAuthException","is_transient":true,"code":4,"fbtra (truncated...)
, 512)
ShareCare.php:105

JonoM\ShareCare\ShareCare->clearFacebookCache()
```

**Comment by phptek** [comment]
Yeah, same here: 

```
    public function onAfterWrite()
    {
        if (!$this->owner->hasMethod('doPublish')) {
            $this->owner->clearFacebookCache();
        }
    }
```

**Comment by phptek** [comment]
A useful fix would be to accept a controller paramter to optionally skip it, when running dev/build

```
...
...
use SilverStripe\Control\Controller;
...

    /**
     * Tell Facebook to re-scrape this URL, if it is accessible to the public.
     */
    public function clearFacebookCache()
    {
        if (Controller::curr()->getRequest()->param('SkipShareCare')) {
            return;
        }
        ....
        ....
```

**Comment by phptek** [comment]
Patched with above PR. It uses an optionally passed GET param, but could equally be configured to accept something from `Config` too. Tested with a dev/build process I have takes ~10m to run (SS3 > 4 upgrade)

**Comment by TheBnl** [comment]
We could also check if 'dev/build' is part of the url, otherwise this would mean ?SkipShareCare=1 should always be added on the url. But maybe there is an incentive to trigger Facebook scraping on dev/build ? I don't think that should be the default behaviour.

**Comment by jonom** [comment]
Certainly wasn't the intention for dev/build to trigger a scrape, but if your build process is publishing all your pages for some reason, it would (and arguably should) trigger a re-scrape to prevent Facebook hanging on to stale representations of those pages. Clearly the current approach doesn't work though when you have lots of pages requesting a fresh scrape at once.

@phptek thanks for your patch but I don't really like the GET param approach as it doesn't allow you to opt out without changing the build URL. Can we think of some other ideas?

One approach I was thinking of was adding a `ShouldClearFacebookCache()` method, which basically just returns `true`, but includes an extension point to let you change that value according to your own requirements. So for example if you want to skip this on builds you could check the current controller and return `false` if a build is happening. (The `clearFacebookCache()` method would call this and only continue if it gets `true` back.) Although... this is already an extension so I guess we can't put an extension point in it 🤔. Might need to just have `ShouldClearFacebookCache()` return true then, and users can override that method on Page etc. with their own logic. Not as flexible but should work okay.

Probably would still be worth having a `ClearFacebookCache` config option so you can easily opt out altogether if you want.

Also, this should really only happen on production environments. Dev and test environments generally won't be publicly accessible, but if they are we probably don't want to advertise their existence. This functionality is designed to refresh Facebook's cache, but if a page isn't already present I guess it would add it, so that could be detrimental. Either way, no point wasting time with a redundant http request. So maybe we only scrape if `Director::isLive() == true`?

**Comment by phptek** [comment]
I don't like the GET param either, I needed to get something going quickly and a PR seems to have done the trick in stimulating conversation about it!

So here's where we're at:

* Separate method that returns a bool 
* Doesn't run in Dev
* Can optionally be enabled/disabled by devs using YML
* Anything else?

**Comment by jonom** [comment]
* ~Doesn't run in Dev~ Only runs in Live (don't run in Test either)

I think that covers it, but if you're going to tackle this and feel like having a look at https://github.com/jonom/silverstripe-share-care/issues/18 at the same time, feel free! 😄

**Comment by phptek** [comment]
This issue still occurs in PROD. How do we limit the requests back to Facebook? Or does this feature need to happen only on CMS publish, NOT on dev/build _at all_?

**Comment by phptek** [comment]
Can this be re-opened please?

**Comment by jonom** [comment]
Do you know why your build process is causing your pages to write and/or publish? That's certainly not the default behaviour. Is another module causing that? Maybe try a build with xdebug on and get a stacktrace to see what is triggering the write? Or stick a `Backtrace::backtrace();` in the share care module?

As for a solution, can you override `doClearFacebookCache()` on your Page model and check if the current request is for a build and return false if so?
